### ISSUE TITLE
documentation of configuring parallel parameters

### ISSUE THREAD

**Issue by yuewuo** [yuewuo/fusion-blossom#34]
The tutorial documentation of parallel computing is missing. Write the documentation of configuration graph partitions and fusion plans according to the descriptions in the paper [1]. The documentation should be placed in `tutorial/src`.

Note that in order to improve speed, it's required that each partition contains the vertices with continuous indices. This is always achievable by reordering vertices. By designing a better interface in Python, maybe we could hide this complexity, by always letting user to describe partitions as a collection of vertices instead of a continuous indices region?

[1] Wu, Yue, and Lin Zhong. "Fusion blossom: Fast mwpm decoders for qec." 2023 IEEE International Conference on Quantum Computing and Engineering (QCE). Vol. 1. IEEE, 2023.

**Comment by YangLiuWillow** [comment]
Hi, I just submitted a PR :)

**Comment by yuewuo** [comment]
Thanks Willow! The documentation is great!
