### ISSUE TITLE
Rust programming: fix build error in latest rust compiler

### ISSUE THREAD

**Issue by yuewuo** [yuewuo/fusion-blossom#36]
In fusion blossom implementation, we use an optional feature `dangerous_pointer` to enable raw pointer in the graph instead of `RwLock` to improve the performance (by almost 2x). However, compiling the code with the latest Rust compiler will give the following error.

```sh
error: casting `&T` to `&mut T` is undefined behavior, even if the reference is unused, consider instead using an `UnsafeCell`
```

This could lead to undefined behavior, so please fix this with an implementation using `UnsafeCell`. For details please check [https://doc.rust-lang.org/book/ch15-05-interior-mutability.html]() and [https://doc.rust-lang.org/std/cell/struct.UnsafeCell.html]().

To test your modification, modify `rust-toolchain.toml` to `channel = "nightly"` (removing the version). Also you need to install the latest Rust compiler by running `rustup update`.

**Comment by atomgardner** [comment]
Is there an easy way to check whether our solutions hurt the benchmarks?

**Comment by atomgardner** [comment]
@yuewuo, could you assign this issue to me so the UF bot can keep score? :)

**Comment by yuewuo** [comment]
> Is there an easy way to check whether our solutions hurt the benchmarks?

A relatively easy check is to run the script in `benchmark/paper_parallel_fusion_blossom/decoding_time_d/run_fusion.py`. You can reduce the number of code distances to e.g. [3, 5, 7, 9, 11]. Running the two versions (your PR and the repo before the PR) should give a sense of how much it changes the benchmark.

**Comment by yuewuo** [comment]
@atomgardner I think there is any place that needs this fix. When you run `cargo clippy --features=dangerous_pointer -- -Dwarnings`. It is unsounds behavior as explained in https://rust-lang.github.io/rust-clippy/master/index.html#mut_from_ref. Would you please look into this? Thanks.
